[project]
name = "oceandata-notebooks"
version = "0.1.0"
description = "Oceandata Jupyter Notebook Tutorials"
requires-python = ">=3.9"
readme = "README.md"
license = {text = "Apache-2.0"}

[[project.authors]]
name = "Anna Windle DiPaola"
email = "anna.windledipaola@nasa.gov"

[[project.authors]]
name = "Ian Carroll"
email = "ian.t.carroll@nasa.gov"

[[project.authors]]
name = "Guoqing Wang"
email = "guoqing.wang@nasa.gov"

[[project.authors]]
name = "Carina Poulin"
email = "carina.poulin@nasa.gov"

[[project.authors]]
name = "Sean Foley"
email = "sean.r.foley@nasa.gov"

[project.urls]
Homepage = "https://oceancolor.gsfc.nasa.gov/resources/docs/tutorials/"
Repository = "https://github.com/gsfc-oel/oceandata-notebooks"
Issues = "https://github.com/gsfc-oel/oceandata-notebooks/issues"

[tool.jupytext]
notebook_metadata_filter = "-all"
cell_metadata_filter = "-all,scrolled"

[tool.jupytext.formats]
"notebooks/" = "ipynb"
"src/" = "py"

[tool.hatch.envs.default]
detached = true
dependencies = [
    "earthaccess",
    "xarray"
]

[tool.hatch.envs.dev]
extra-dependencies = [
    "ipykernel",
    "jupyter-book",
    "jupytext"
]

[tool.hatch.envs.jb]
detached = true
system-site-packages = true
dependencies = [
    "jupyter-book"
]

[tool.hatch.envs.jb.scripts]
build = """
    jb build --path-output=. --config=src/_config-exec.yml src && \
    jb build --path-output=docs src && \
    rsync -a docs/_build/jupyter_execute/ _build/html/_sources/
    """
