[project]
  name = "oceandata-notebooks"
  version = "0.2.0"
  description = "Oceandata Jupyter Notebook Tutorials"
  requires-python = ">=3.9"
  readme = "README.md"
  dependencies = [
    # every package used in an import or by a backend (e.g. h5netcdf)
    "cartopy>=0.22.0",
    "cmocean>=4.0.3",
    "dask[distributed]>=2024.4.1",
    "earthaccess>=0.11.0",
    "h5netcdf>=1.3.0",
    "holoviews>=1.19.1",
    "hvplot>=0.9.2",
    "matplotlib>=3.8.4",
    "netcdf4>=1.6.5",
    "numba>=0.60.0",
    "pandas>=2.2.1",
    "pillow>=10.4.0",
    "pvlib>=0.11.1",
    "pyproj>=3.6.1",
    "scipy>=1.13.1",
    "seaborn>=0.13.2",
    "tqdm>=4.66.5",
    # "torch>=2.4.1",
    # "torchvision>=0.19.0",
    "xarray>=2024.3.0",
  ]
  [project.optional-dependencies]
    kernel = [
      # extras for src/setup.py
      "bash-kernel>=0.9.3",
      "ipykernel>=6.29.3",
      "ipywidgets>=8.1.2",
    ]
    hub = [
      # extras for hub/requirements.txt
      "async-timeout>=4.0.3", # TODO: possible unlisted dep of jupyter-vscode-proxy?
      "bash-kernel>=0.9.3",
      "dask-labextension>=7.0.0",
      "geopandas>=1.0.1",
      "geoviews>=1.12.0",
      "gh-scoped-creds>=4.1",
      "jupyter-vscode-proxy>=0.6",
      "jupyterlab-git>=0.50.1",
      "jupyterlab-h5web>=12.3.0",
      "rasterio>=1.4.1",
      "rioxarray>=0.15.0",
      "scikit-image>=0.24.0",
      "scikit-learn>=1.5.2",
      "zarr>=2.18.2",
    ]
    dev = [
      # extras for maintainer actions
      "jupyter-book>=1.0.2",
      "jupyter-repo2docker>=2024.7.0",
      "jupytext>=1.16.4",
      "pre-commit>=4.0.1",
      "ruff>=0.6.9",
      "tomlkit>=0.13.2",
    ]
  [[project.maintainers]]
    name = "Ian Carroll"
    email = "ian.t.carroll@nasa.gov"
  [project.license]
    text = "Apache-2.0"
  [project.urls]
    Repository = "https://github.com/gsfc-oel/oceandata-notebooks"
    Issues = "https://github.com/gsfc-oel/oceandata-notebooks/issues"
  [[project.authors]]
    name = "Ian Carroll"
    email = "ian.t.carroll@nasa.gov"
  [[project.authors]]
    name = "Anna Windle DiPaola"
    email = "anna.windledipaola@nasa.gov"
  [[project.authors]]
    name = "Sean Foley"
    email = "sean.r.foley@nasa.gov"
  [[project.authors]]
    name = "Carina Poulin"
    email = "carina.poulin@nasa.gov"
  [[project.authors]]
    name = "Guoqing Wang"
    email = "guoqing.wang@nasa.gov"

[tool.jupytext]
  notebook_metadata_filter = "all,-kernelspec"
  cell_metadata_filter = "all,-trusted"
  [tool.jupytext.formats]
    notebooks = "ipynb"
    src = "py"

[tool.ruff]
  extend-include = ["_build"]
  [tool.ruff.lint]
    extend-select = ["I", "D"]
    ignore = ["D1", "D417", "F841"] # TODO: reconsider F841

[tool.uv]
  #   #index-strategy = "unsafe-best-match"
  #   extra-index-url = ["https://download.pytorch.org/whl/cpu"]
