[project]
name = "oceandata-notebooks"
version = "0.1.0"
description = "Oceandata Jupyter Notebook Tutorials"
urls.Repository = "https://github.com/gsfc-oel/oceandata-notebooks"
urls.Issues = "https://github.com/gsfc-oel/oceandata-notebooks/issues"
requires-python = ">=3.9"
readme = "README.md"
license = { text = "Apache-2.0" }
dependencies = [
    "cartopy>=0.22.0",
    "cmocean>=4.0.3",
    "dask[distributed]>=2024.4.1",
    "earthaccess>=0.10.0",
    "h5netcdf>=1.3.0",
    "hvplot>=0.9.2",
    "ipykernel>=6.29.3",
    "ipywidgets>=8.1.2",
    "matplotlib>=3.8.4",
    "netcdf4>=1.6.5",
    "pandas>=2.2.1",
    "scipy>=1.13.1",
    # "torch>=2.4.1",
    # "torchvision>=0.19.0",
    "xarray>=2024.3.0",
]
optional-dependencies.dev = [
    "jupyter-book>=1.0.2",
    "jupyter-repo2docker>=2024.7.0",
    "jupytext>=1.16.4",
    "tomlkit>=0.13.2",
]

# [tool.uv]
# #index-strategy = "unsafe-best-match"
# extra-index-url = ["https://download.pytorch.org/whl/cpu"]

[tool.jupytext]
notebook_metadata_filter = "-all"
cell_metadata_filter = "-all,scrolled,tags"

[tool.jupytext.formats]
"notebooks" = "ipynb"
"src/notebooks" = "py"

[[project.authors]]
name = "Ian Carroll"
email = "ian.t.carroll@nasa.gov"

[[project.authors]]
name = "Anna Windle DiPaola"
email = "anna.windledipaola@nasa.gov"

[[project.authors]]
name = "Sean Foley"
email = "sean.r.foley@nasa.gov"

[[project.authors]]
name = "Carina Poulin"
email = "carina.poulin@nasa.gov"

[[project.authors]]
name = "Guoqing Wang"
email = "guoqing.wang@nasa.gov"
