only_build_toc_files: true
execute:
  timeout: -1
  run_in_temp: true
  execute_notebooks: cache
sphinx:
  local_extensions:
    source_button: _ext
  config:
    # templates_path:
    #   - _templates
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py
        - true # use CommonMark for markdown cells in notebooks
