title: My sample book
only_build_toc_files: true
execute:
  execute_notebooks: off
  run_in_temp: true
sphinx:
  config:
    # templates_path:
    #   - _templates
    myst_commonmark_only: true
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py
