title: My sample book
only_build_toc_files: true
execute:
  execute_notebooks: auto
  run_in_temp: true
sphinx:
  local_extensions:
    source_button: _ext
  config:
    templates_path:
      - _templates
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py
        - true # use CommonMark for markdown cells in notebooks
