only_build_toc_files: true
execute:
  # no cell timeout
  timeout: -1
  # no reuse of downloads, etc.
  run_in_temp: true
  # re-use outputs (when none of the code cells change)
  execute_notebooks: cache
sphinx:
  local_extensions:
    source_button: _ext
  config:
    # templates_path:
    #   - _templates
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py
        # use CommonMark (not MyST Markdown)
        - true
