only_build_toc_files: true
execute:
  timeout: -1  # no cell timeout
  run_in_temp: true  # no reuse of downloads, etc.
  execute_notebooks: off  # re-use outputs (when none of the code cells change)
sphinx:
  config:
    templates_path:
      - _templates
    myst_commonmark_only: true
# FIXME: use CommonMark (not MyST Markdown) ... maybe not jupyter book but what its built on?
